server:
  port: 8401

spring:
  application:
    name: miya-monitor-Admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  cloud:
    nacos:
      discovery:
        namespace: dfa47935-e89b-40a9-a489-326e550388e6
        server-addr: http://172.81.245.35:8001
  security:
    user:
      name: miya
      password: 123456