server:
  port: 8401

spring:
  application:
    name: miya-monitor-Admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  cloud:
    nacos:
      discovery:
        namespace: 462daff6-139a-48bd-a529-39ef27b87745
        server-addr: http://www.miya-l.top:8001
  security:
    user:
      name: miya
      password: 123456