server:
  port: 8401

spring:
  application:
    name: miya-monitor-Admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  cloud:
    nacos:
      discovery:
        namespace: 8f9990b9-483a-4728-98c7-32e7cd04d475
        server-addr: localhost:8001
  security:
    user:
      name: miya
      password: 123456