server:
  port: 8301

spring:
  application:
    name: miya-gateway
  # admin 监控
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: miya
        password: 123456
  cloud:
    nacos:
      discovery:
        namespace: 8f9990b9-483a-4728-98c7-32e7cd04d475
        server-addr: localhost:8001
    gateway:
      routes:
        - id: miya-auth
          uri: lb://miya-auth
          predicates:
            - Path=/auth/**
        - id: miya-system
          uri: lb://miya-system
          predicates:
            - Path=/system/**
        - id: miya-pay
          uri: lb://miya-pay
          predicates:
            - Path=/pay/**
      default-filters:
        - StripPrefix=1
  autoconfigure: # 关闭数据库自动装配
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# admin 监控
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS