server:
  port: 8301

spring:
  application:
    name: miya-gateway
  # admin 监控
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: miya
        password: 123456
  cloud:
    nacos:
      discovery:
        namespace: 462daff6-139a-48bd-a529-39ef27b87745
        server-addr: http://www.miya-l.top:8001
    gateway:
      routes:
        - id: miya-auth
          uri: lb://miya-auth
          predicates:
            - Path=/auth/**
        - id: miya-system
          uri: lb://miya-system
          predicates:
            - Path=/system/**
        - id: miya-pay
          uri: lb://miya-pay
          predicates:
            - Path=/pay/**
      default-filters:
        - StripPrefix=1
  autoconfigure: # 关闭数据库自动装配
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
