server:
  port: 8101
spring:
  application:
    name: miya-auth
  cloud:
    nacos:
      discovery:
        namespace: 8f9990b9-483a-4728-98c7-32e7cd04d475
        server-addr: localhost:8001
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
